### ISSUE TITLE
AWS Provider

### ISSUE THREAD

**Issue by sadek-hussein** [micro-frontends-demo/infra#1]
Error: No valid credential sources found for AWS Provider.

**Comment by camjackson** [comment]
Yes, to run the terraform code you need to have set up access to the AWS API, just as you would if you were using the AWS CLI.

**Comment by sadek-hussein** [comment]
> Yes, to run the terraform code you need to have set up access to the AWS API, just as you would if you were using the AWS CLI.

Noted Thank you
